RFC: 256 ReactCDK: Add JSX/TSX Support
aws/aws-cdk-rfcs pull request #258
Opened 2020-09-27 14:05 UTC by pfeilbr

* Tracking issue: #256
* [Rendered version](https://github.com/pfeilbr/aws-cdk-rfcs/blob/510d68da2f/text/0256-react-cdk-add-jsx-tsx-support.md)

---

_By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache-2.0 license_

2020-10-05 09:32 UTC, eladb requested changes
How do we determine the construct IDs? It seems like they are implicitly determined somehow but I haven't seen any discussion about this.

I think a prototype is in order in order to flush out the details.

2021-01-11 16:13 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +      "body: JSON.stringify(event)
```suggestion
      "body": JSON.stringify(event)
```

2021-01-11 16:13 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +      "body: JSON.stringify(event)
```suggestion
      "body": JSON.stringify(event)
```

2021-01-11 16:28 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +const MyCloudFrontDistribution = (
Shouldn't all components be a function? e.g.
```suggestion
const MyCloudFrontDistribution = () => (
```

2021-01-11 16:36 UTC, pfeilbr commented
Thanks @iamandrewluca for the fixes.

2021-01-11 21:00 UTC, eladb requested changes
I think from a design perspective we should aim for this to support any CDK (cdktf/cdk8s) and not just the AWS CDK.

2021-01-11 21:00 UTC, eladb commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +
Can you add to the README what would be the next steps users need to take in order to synth and deploy this app?

2021-01-11 21:00 UTC, eladb commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +* CDK is associated and tied to AWS brand.  AWS tends to support all "popular" frameworks equally.  Favoring one might
I think that's not a concern. Having support for multiple languages and idioms is actually a tenet of the CDK, and as such this proposal enhances the ecosystem.

2021-01-11 21:00 UTC, eladb commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +[via]((https://twitter.com/emeshbi/status/1305017904027643906?s=20)) @eladb
This is possible but probably the hardest part. Constructs often offer imperative APIs that won't be expressive JSX but can technically still be accessible from code.

The work we did on [decdk](https://www.npmjs.com/package/decdk) can be leveraged.

2021-01-12 14:31 UTC, iamandrewluca requested changes

2021-01-12 14:31 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +const EchoLambda = (
```suggestion
const EchoLambda = () => (
```

2021-01-12 14:31 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +const EchoApi = (
```suggestion
const EchoApi = () => (
```

2021-01-12 14:31 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +const MyApp = (
```suggestion
const MyApp = () => (
```

2021-01-12 14:31 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +ReactCDK.render(MyApp, {region: 'us-east-1'})
```suggestion
ReactCDK.render(<MyApp />, {region: 'us-east-1'})
```

2021-01-12 14:56 UTC, iamandrewluca commented on text/0256-react-cdk-add-jsx-tsx-support.md
> +    })
In my opinion the code for a lambda should still be a separated file, and be passed to `<Lambda />` as a prop as a path to the code

e.g.
```tsx
<Lambda handler="src/handler" />
```

2021-01-12 15:01 UTC, iamandrewluca commented
I see 2 ways how this can be done.

- JSX is transformed into direct calls to CDK constructs
- JSX istransformed directly into CloudFormation (yml/json) format

2021-01-22 11:21 UTC, iamandrewluca commented
So we need to create a JSX transformer that respects https://github.com/aws/constructs interface

2021-07-20 12:59 UTC, nija-at commented
RFC Bar Raiser: eladb@

2021-08-01 08:39 UTC, eladb commented
@pfeilbr I am closing this for now. Please reach out if you are interested to continue working on this.

2021-08-01 08:39 UTC, closed without merging