RFC 77, RFC 264: CloudFormation Registry Imports
aws/aws-cdk-rfcs pull request #266
Opened 2020-11-05 14:09 UTC by rix0rrr

These are two distinct RFCs for two distinct features, but we might as
well work on the docs at the same time. Hence, one PR.

* Tracking issue: #77 - importing external resources
* [Rendered version](/huijbers/0264-0077-cloudformation-registry/text/0077-import-external-resources.md)

* Tracking issue: #264 - codegen off the new registry schema
* [Rendered version](/huijbers/0264-0077-cloudformation-registry/text/0264-registry-schema-codegen.md)

---

_By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache-2.0 license_

2020-11-13 07:02 UTC, eladb requested changes
Great RFCs! Let's definitely have a discussion as part of these two RFCs around whether we want to continue to vend CFN resources as part of the AWS construct library or just use them as an implementation detail.

2020-11-13 07:02 UTC, eladb commented on text/0264-registry-schema-codegen.md
> +  in the schema. This can mostly be based on `json2jsii`, although we will
Let's definitely try to bake as much of the capabilities into Json2jsii so we get the most leverage for other CDKs (and jsii-based projects).

2020-11-25 13:23 UTC, eladb requested changes
We should make sure to take the recently launched CloudFormation modules into the `cdk import` feature. I'd like to be able to do something like `cdk import MyCompany::S3::Bucket::MODULE`

2021-07-20 12:58 UTC, nija-at commented
@rix0rrr - can you check if this is superceded by https://github.com/aws/aws-cdk-rfcs/pull/356.

2021-11-03 08:51 UTC, rix0rrr commented
> @rix0rrr - can you check if this is superceded by #356.

From the title, #356 would build on the work proposed here, but the work here would also be useful to people importing constructs in their own accounts.

2021-11-03 12:24 UTC, eladb commented
FYI, this is now being implemented and published under [cdklabs/cdk-import](https://github.com/cdklabs/cdk-import).

@rix0rrr I am wondering if it's worth leaving this RFC open or we can merge it for now and continue iterating on the code?

2023-06-29 15:39 UTC, merged