RFC 400: RUM AppMonitor L2 Construct
aws/aws-cdk-rfcs pull request #408
Opened 2022-02-16 16:02 UTC by WinterYukky

This is a request for comments about RUM AppMonitor L2 Construct. See #400  for
additional details. 

APIs are signed off by @madeline-k .

---

_By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache-2.0 license_

2022-02-16 16:13 UTC, madeline-k commented
Thanks for opening this Pull Request, @WinterYukky! I have not had a chance to review the APIs yet, so this is not signed off yet. I plan to review this later this week.

2022-03-22 20:37 UTC, madeline-k requested changes
This is a great start @WinterYukky! I think for next steps, you should open a PR to aws-cdk with the minimum feature set. Then we can see it in action as an experimental L2 before finalizing this RFC. 

The minimum feature set here should just be the AppMonitor construct with default behavior of creating the Identity Pool for you. We can add on other features and other methods of authorization in an iterative manner.

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +By default, AppMonitor creates a new Amazon Cognito identity pool and uses it to authenticate the put event.
A suggestion to make it clear to users what exactly is happening. 
```suggestion
By default, when you create a new `AppMonitor` construct, CDK creates a new Amazon Cognito identity pool. This identity pool is used by CloudWatch to...
```

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +that unlike the management console, the code snippets do not have `<script>` tags because the CDK expects them to be automatically embedded in the application.
Can you explain further why the generated code snippet should not include the `<script>` tag?

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +AppMonitor generates a code snippet that looks like to create on the management console. Note, however,
I think this sentence is missing something?

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +const codeSnippet = appMonitor.generateCodeSnippet('CodeSnippet');
How would the customer then use the code snippet? We should show an example of how they can take this an actually insert it into their application code.

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +By using S3 Deployment, you can automate embeded to your application.
```suggestion
By using S3 Deployment, you can automate embedding the CloudWatch RUM code snippet into your application.
```

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +});
Practically speaking, I don't think developers are going to write raw HTML inline like this. Also part of this is boilerplate, like specifying the script name `rum.js` twice. Can we make this simpler? And closer to a real-world scenario?

2022-03-22 20:37 UTC, madeline-k commented on text/0400-appmonitor-l2.md
> +#### Type Definetions
```suggestion
#### Type Definitions
```

2022-04-09 14:29 UTC, WinterYukky commented
Hello @madeline-k.
I fixed RFC and created the PR https://github.com/aws/aws-cdk/pull/18364 with the minimum feature set .
Cloud you review the PR?

2023-12-19 14:59 UTC, closed without merging